config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#landing"

  get "/home" => "home#landing"

  post "/auth/auth0", as: "login"
  get "/auth/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/logout" => "logout#logout"

  resources :opportunity_applications do
    get :review, on: :member
  end
  resources :volunteer_opportunities
  resources :profiles
  resources :settings
  resources :events

  get "/apply" => "dashboard#apply"
  get "/apply/success" => "dashboard#success"
  get "/dashboard" => "dashboard#elevated_user_dashboard"

  get "help" => "home#help"
  get "code_of_conduct" => "home#code_of_conduct"
  get "privacy_policy" => "home#privacy_policy"

  get "reports/export_opportunity_applications" => "report#export_opportunity_applications"
  get "reports/export_opportunity_application_coordinator_comments" => "report#export_opportunity_application_coordinator_comments"
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  after_action :skip_authorization

  def landing
    @active_event = policy_scope(Event).first_active

    return unless @active_event

    registration_start_date = @active_event.registration_start_date
    if Date.today < registration_start_date
      registration_start_date = registration_start_date.strftime("%A, %B #{registration_start_date.day.ordinalize}")
      @registration_text = "Registration opens on #{registration_start_date}"
    end
    start_date = @active_event.start_date
    @festival_start_date = start_date.strftime("%B #{start_date.day.ordinalize}")
    end_date = @active_event.end_date
    @festival_end_date = end_date.strftime("%B #{end_date.day.ordinalize}")
  end

  def code_of_conduct; end

  def about; end

  def help; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/landing.html.erb
<% if @registration_text %>
<section class="section-dates section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h3><%= @registration_text %></h3>
    </div>
  </div>
</section>
<% end %>

<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <header class="section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone">
    <%= image_tag '/2023-logo.png', style: 'max-width:90%;max-height:90%;' %>
  </header>
  <div class="mdl-card mdl-cell mdl-cell--9-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone">
    <div class="mdl-card__supporting-text">
      <h4>Volunteer at the Ottawa Jazz Festival</h4>
      <p>
        The Ottawa International Jazz Festival is a celebration of the world's best jazz artists each
        summer in the heart of downtown Ottawa.
      </p>
    </div>
    <div class="mdl-card__actions">
      <a href="http://ottawajazzfestival.com/" target="_BLANK">Official Website</a>
      <a href="http://ottawajazzfestival.com/map" target="_BLANK">Map</a>
      <a href="http://ottawajazzfestival.com/faqs" target="_BLANK">Jazz Festival FAQs</a>
      <%= link_to 'Help', help_path %>
    </div>
  </div>
</section>

<section class="section-dates section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h4 class="mdl-cell mdl-cell--12-col">
        <% if @festival_start_date %>
          Volunteers are needed between <%= @festival_start_date %>
          and <%= @festival_end_date %>.
        <% else %>
          We are not actively recruiting right now. Please check again later.
        <% end %>
      </h4>
    </div>
  </div>
</section>

<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h4 class="mdl-cell mdl-cell--12-col">How to Apply</h4>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-user"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--3-col-phone">
        <h5>Sign Up</h5>
        You can use sign up using Facebook, Twitter, Google, Microsoft to avoid remembering another password or use your email.
        After signing up, you will be redirected to the application page.
      </div>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-address-book"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--3-col-phone">
        <h5>Profile</h5>
        Tell us about yourself and what you can do.
      </div>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-calendar-check"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--3-col-phone">
        <h5>Availability</h5>
        Indicate which dates you're available to volunteer on.
      </div>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-list-ol"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--7-col-tablet mdl-cell--3-col-phone">
        <h5>Apply to opportunities</h5>
        Indicate and rank which volunteer opportunities interest you.
      </div>
    </div>
    <div class="mdl-card__actions">
      <%= link_to 'Login / Sign up', login_path, method: :post, class: '' %>
      <%= link_to 'Volunteer Opportunities', volunteer_opportunities_path %>
      <%= link_to 'Code of Conduct', code_of_conduct_path %>
    </div>
  </div>
</section>

app/views/home/privacy_policy.html.erb
<h1>
Privacy Policy
<small>Last Edited on 2021-04-03</small>
</h1>
<p>
  This privacy policy has been compiled to better serve those who are concerned with how their 'Personally identifiable information' (PII) is being used online. PII is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context. Please read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance with our website.
</p>
<h3>What personal information do we collect from the people that visit our website?</h3>
<p>
  When applying to volunteer, you will be asked to enter your name, email address, mailing address, phone numbers, age range, t-shirt size, emergency contact information, and skills that apply to your application.
</p>
<h3>When do we collect information?</h3>
<p>
  We collect information from you when you register on our site, respond to a survey, fill out a form  or enter information on our site.
</p>
<h3>How do we use your information? </h3>
<p>
  We may use the information we collect from you when you register, and apply in the following ways:
  <ul>
    <li>evaluate your application to volunteer,</li>
    <li>call you in regards to your application,</li>
    <li>email you in regards to volunteer meetings,</li>
    <li>etc.</li>
  </ul>
</p>
<h3>How do we protect visitor information?</h3>
<p>
  Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive information you supply is encrypted via Secure Socket Layer (SSL) technology.
</p>
<h3>Do we use 'cookies'?</h3>
<p>
  Yes. Cookies are small files that a site or its service provider transfers to your computer's hard drive through your Web browser (if you allow) that enables the site's or service provider's systems to recognize your browser and capture and remember certain information.
</p>
<p>
  For instance, we use cookies to remember who you are between visits and keep track of actions you're authorized to perform.
</p>
<p>
  You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser (like Internet Explorer) settings. Each browser is a little different, so look at your browser's Help menu to learn the correct way to modify your cookies.
</p>
<p>
  If you disable cookies, it is likely that most features will not function properly.
</p>
<h3>Third Party Disclosure</h3>
<p>
  We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information.
</p>
<p>
  We do, however, use a third party to handle authentication (sign-up and sign-in) and authorization. They store OAuth tokens and data from providers (Google, Microsoft, Twitter, Facebook), and email/password combos if you chose that method.
</p>
<h3>Third party links</h3>
<p>
  <a href="https://auth0.com/">Auth0</a>
</p>
<h3>Advertisement</h3>
<p>
  We do not display advertisements on our website and do not plan to in the future.
</p>
<h3>How does our site handle do not track signals?</h3>
<p>
  We don't honor do not track signals and do not track, plant cookies, or use advertising when a Do Not Track (DNT) browser mechanism is in place. We don't honour them as we do not track our users.
</p>
<h3>Does our site allow third party behavioral tracking?</h3>
<p>
  No, we do not. Nor de we plan to in the future.
</p>
<h3>Fair Information Practices</h3>
<p>
  The Fair Information Practices Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe. Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information.
</p>
<h4>In order to be in line with Fair Information Practices we will take the following responsive action, should we detect that a data breach has occurred:</h4>
<p>
  <ul>
    <li>notify our users via email immediately via email and in site notifications </li>
  </ul>
</p>
<h3>Contacting Us</h3>
<p>
  If there are any questions regarding this privacy policy you may contact us using the information below.
  <address>
    <a href="https://seanfloyd.ca">Sean Floyd</a><br>
    <a href="mailto:ottawajazzify@gmail.com">ottawajazzify@gmail.com</a><br>
    Paris, France
  </address>
</p>

app/views/home/show.html.erb
<section class="section-dates section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h3><%= @registration_text %></h3>
    </div>
  </div>
</section>

<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <header class="section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone" style="background-color: yellow;">
    <%= image_tag 'http://ih.constantcontact.com/fs184/1011286729170/img/552.gif?a=1113439043233', style: 'max-width:90%;max-height:90%;' %>
  </header>
  <div class="mdl-card mdl-cell mdl-cell--9-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone">
    <div class="mdl-card__supporting-text">
      <h4>Volunteer at the Ottawa Jazz Festival</h4>
      <p>
        The Ottawa International Jazz Festival is a celebration of the worlds best jazz artists each
        summer in the heart of downtown Ottawa.
      </p>
    </div>
    <div class="mdl-card__actions">
      <a href="http://ottawajazzfestival.com/" target="_BLANK">Official Website</a>
      <a href="http://ottawajazzfestival.com/map" target="_BLANK">Map</a>
    </div>
  </div>
</section>

<section class="section-dates section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h4 class="mdl-cell mdl-cell--12-col">
        Volunteers are needed between <%= @festival_start_date %>
        and <%= @festival_end_date %>.
      </h4>
    </div>
  </div>
</section>

<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <div class="mdl-card mdl-cell mdl-cell--12-col">
    <div class="mdl-card__supporting-text mdl-grid mdl-grid--no-spacing">
      <h4 class="mdl-cell mdl-cell--12-col">How to Apply</h4>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-user"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        <h5>Sign Up</h5>
        You can use sign up using Facebook, Twitter, Google, Microsoft to avoid remembering another password or use your email.
        After signing up, you will be redirected to the application page.
      </div>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-address-book-o"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        <h5>Profile</h5>
        Tell us about yourself and what you can do.
      </div>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-calendar-check-o"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        <h5>Availability</h5>
        Indicate which dates you're available to volunteer on.
      </div>
      <div class="font-icon-step-container mdl-cell mdl-cell--1-col mdl-cell--1-col-phone">
        <div class="font-icon-step"><i class="fa fa-list-ol"></i></div>
      </div>
      <div class="section__text mdl-cell mdl-cell--11-col-desktop mdl-cell--6-col-tablet mdl-cell--3-col-phone">
        <h5>Apply to opportunities</h5>
        Indicate and rank which volunteer opportunities interest you.
      </div>
    </div>
    <div class="mdl-card__actions">
      <a onclick="lock.show()">Sign up</a>
      <%= link_to 'Volunteer Opportunities', volunteer_opportunities_path %>
      <%= link_to 'Code of Conduct', code_of_conduct_path %>
    </div>
  </div>
</section>

<section class="section-map section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <header class="section__play-btn mdl-cell mdl-cell--12-col mdl-color-text--white">
    <iframe src="https://mapsengine.google.com/map/embed?mid=zJSsAHwDnr1g.kS6cP1RqYa_Y"></iframe>
  </header>
</section>

<section class="section-map section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <!-- <header class="section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone mdl-color-text--white"> -->
  <header class="section__play-btn mdl-cell mdl-cell--12-col mdl-color-text--white">
    <iframe src="https://www.youtube.com/embed/4_L5rTpI4TA" frameborder="0" allowfullscreen></iframe>
  </header>
</section>