config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#landing"

  get "/home" => "home#landing"

  post "/auth/auth0", as: "login"
  get "/auth/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/logout" => "logout#logout"

  resources :opportunity_applications do
    get :review, on: :member
  end
  resources :volunteer_opportunities
  resources :profiles
  resources :settings
  resources :events

  get "/apply" => "dashboard#apply"
  get "/apply/success" => "dashboard#success"
  get "/dashboard" => "dashboard#elevated_user_dashboard"

  get "help" => "home#help"
  get "code_of_conduct" => "home#code_of_conduct"
  get "privacy_policy" => "home#privacy_policy"

  get "reports/export_opportunity_applications" => "report#export_opportunity_applications"
  get "reports/export_opportunity_application_coordinator_comments" => "report#export_opportunity_application_coordinator_comments"
end

app/models/volunteer_opportunity.rb
# frozen_string_literal: true

class VolunteerOpportunity < ApplicationRecord
  has_many :accepted_applications, foreign_key: :accepted_volunteer_opportunity_id, class_name: "OpportunityApplication"

  def title=(val)
    self[:title] = val.strip
  end

  class << self
    def visible
      where(visible: true)
    end

    def applied_to_
      applied_to(OpportunityApplication.all)
    end

    def applied_to(scope)
      return none if scope.empty?

      where(id: OpportunityApplication.uniq_choice_ids(scope: scope))
    end

    def visible_or_applied_to(scope)
      visible
        .or(applied_to(scope))
    end
  end
end

app/controllers/volunteer_opportunities_controller.rb
# frozen_string_literal: true

class VolunteerOpportunitiesController < ApplicationController
  before_action :set_volunteer_opportunity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action(except: [:show, :destroy]) { authorize VolunteerOpportunity }

  # GET /volunteer_opportunities
  # GET /volunteer_opportunities.json
  def index
    @volunteer_opportunities = policy_scope(VolunteerOpportunity).order(visible: :desc, title: :asc)
  end

  # GET /volunteer_opportunities/1
  # GET /volunteer_opportunities/1.json
  def show
    authorize(@volunteer_opportunity)
  end

  # GET /volunteer_opportunities/new
  def new
    @volunteer_opportunity = VolunteerOpportunity.new
  end

  # GET /volunteer_opportunities/1/edit
  def edit
  end

  # POST /volunteer_opportunities
  # POST /volunteer_opportunities.json
  def create
    @volunteer_opportunity = VolunteerOpportunity.new(volunteer_opportunity_params)

    respond_to do |format|
      if @volunteer_opportunity.save
        format.html { redirect_to(@volunteer_opportunity, notice: "Volunteer opportunity was successfully created.") }
        format.json { render(:show, status: :created, location: @volunteer_opportunity) }
      else
        format.html { render(:new) }
        format.json { render(json: @volunteer_opportunity.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /volunteer_opportunities/1
  # PATCH/PUT /volunteer_opportunities/1.json
  def update
    respond_to do |format|
      if @volunteer_opportunity.update(volunteer_opportunity_params)
        format.html { redirect_to(@volunteer_opportunity, notice: "Volunteer opportunity was successfully updated.") }
        format.json { render(:show, status: :ok, location: @volunteer_opportunity) }
      else
        format.html { render(:edit) }
        format.json { render(json: @volunteer_opportunity.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /volunteer_opportunities/1
  # DELETE /volunteer_opportunities/1.json
  def destroy
    authorize(@volunteer_opportunity)
    @volunteer_opportunity.destroy
    respond_to do |format|
      format.html { redirect_to(volunteer_opportunities_url, notice: "Volunteer opportunity was successfully destroyed.") }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_volunteer_opportunity
    @volunteer_opportunity = VolunteerOpportunity.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the allowlist through.
  def volunteer_opportunity_params
    params.require(:volunteer_opportunity).permit(:title, :objective, :duties_and_responsibilities, :qualifications_and_requirements, :shifts, :visible)
  end
end

app/helpers/volunteer_opportunities_helper.rb
# frozen_string_literal: true

module VolunteerOpportunitiesHelper
end

app/views/volunteer_opportunities/index.html.erb
<h1>Volunteer Opportunities</h1>

<% if policy(VolunteerOpportunity).new? %>
<%= link_to 'New Volunteer Opportunity', new_volunteer_opportunity_path %>
<% end %>

<div class="volunteer_opportunity-cards">
  <% if @volunteer_opportunities.blank? %>
    <h2>There are no opportunities to display yet.</h2>
    <h3><span class="fa fa-frown-o">&nbsp;</span></h3>
  <% else %>
    <% @volunteer_opportunities.each do |volunteer_opportunity| %>
      <div class="volunteer_opportunity-card mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
          <div class="mdl-card__title-text">
            <% if policy(VolunteerOpportunity).edit? %>
              <span class="fa fa-<%= volunteer_opportunity.visible ? 'eye' : 'eye-slash' %>">&nbsp;</span>
            <% end %>
            <span><%= volunteer_opportunity.title %></span>
          </div>
        </div>
        <div class="mdl-card__supporting-text">
          <h6 class='mdl-color-text--pink'>Objective</h6>
          <div class='fr-view'><%= volunteer_opportunity.objective.html_safe %></div>
          <h6 class='mdl-color-text--pink'></h6>
          <h6 class='mdl-color-text--pink'>Shifts</h6>
          <div class='fr-view'><%= volunteer_opportunity.shifts.html_safe %></div>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <%= link_to 'More Info', volunteer_opportunity %>
          <%= link_to 'Apply', apply_path(volunteer_opportunity_id: volunteer_opportunity.id) %>
          <% if policy(VolunteerOpportunity).edit? %>
          <%= link_to 'Edit', edit_volunteer_opportunity_path(volunteer_opportunity) %>
          <% end %>
          <% if policy(volunteer_opportunity).destroy? %>
          <%= link_to 'Destroy', volunteer_opportunity, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/volunteer_opportunities/show.html.erb
<div class="volunteer_opportunity-card mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <div class="mdl-card__title-text">
      <% if policy(VolunteerOpportunity).edit? %>
        <span class="fa fa-<%= @volunteer_opportunity.visible ? 'eye' : 'eye-slash' %>">&nbsp;</span>
      <% end %>
      <span><%= @volunteer_opportunity.title %></span>
    </div>
  </div>
  <div class="mdl-card__supporting-text">
    <h6 class='mdl-color-text--pink'>Objective</h6>
    <div class='fr-view'><%= @volunteer_opportunity.objective.html_safe %></div>
    <h6 class='mdl-color-text--pink'>Duties &amp; Responsibilities</h6>
    <div class='fr-view'><%= @volunteer_opportunity.duties_and_responsibilities.html_safe %></div>
    <h6 class='mdl-color-text--pink'>Qualifications &amp; Requirements</h6>
    <div class='fr-view'><%= @volunteer_opportunity.qualifications_and_requirements.html_safe %></div>
    <h6 class='mdl-color-text--pink'>Shifts</h6>
    <div class='fr-view'><%= @volunteer_opportunity.shifts.html_safe %></div>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <%= link_to 'Back', volunteer_opportunities_path %>
    <% if policy(VolunteerOpportunity).edit? %>
    <%= link_to 'Edit', edit_volunteer_opportunity_path(@volunteer_opportunity) %>
    <% end %>
    <% if policy(@volunteer_opportunity).destroy? %>
    <%= link_to 'Destroy', @volunteer_opportunity, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>