config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#landing"

  get "/home" => "home#landing"

  post "/auth/auth0", as: "login"
  get "/auth/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/logout" => "logout#logout"

  resources :opportunity_applications do
    get :review, on: :member
  end
  resources :volunteer_opportunities
  resources :profiles
  resources :settings
  resources :events

  get "/apply" => "dashboard#apply"
  get "/apply/success" => "dashboard#success"
  get "/dashboard" => "dashboard#elevated_user_dashboard"

  get "help" => "home#help"
  get "code_of_conduct" => "home#code_of_conduct"
  get "privacy_policy" => "home#privacy_policy"

  get "reports/export_opportunity_applications" => "report#export_opportunity_applications"
  get "reports/export_opportunity_application_coordinator_comments" => "report#export_opportunity_application_coordinator_comments"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <section class="about-the-app columns">
      <div class="app-name column has-text-centered">
        <strong><%= appname %></strong> &copy; <%= Time.current.year %>
      </div>
      <div class="author column has-text-centered">
        <%= icon_link_to "#{t('misc.made_by')} Sean Floyd", 'https://seanfloyd.ca', '👨‍💻', class: '' %>
      </div>
      <div class="source-code column has-text-centered">
        <%= icon_link_to t('navigation.source_code'), "https://github.com/SeanLF/jazzfest", '</>', {}, {class: 'has-text-dark'} %>
      </div>
    </section>
    <!-- <nav class=" is-dark">
      <%= icon_link_to t('navigation.home'), root_path, '🏠', class: 'navbar-item' %>
      <%= icon_link_to t('navigation.code_of_conduct'), 'code_of_conduct_path', '✅', class: 'navbar-item' %>
      <%= icon_link_to t('navigation.privacy_policy'), 'privacy_policy_path', '🕵️‍♂️', class: 'navbar-item' %>
      <%= icon_link_to t('navigation.help'), 'help_path', '❓', class: 'navbar-item' %>
      <%= icon_link_to t('navigation.language'), change_language_path, '🌎', class: 'navbar-item', 'data-turbolinks': 'false' %>
    </nav> -->
  </div>
</footer>

app/views/layouts/_nav_links.html.erb
<%= link_to 'Home', root_path, class:"mdl-navigation__link" %>
<%= link_to 'Volunteer Opportunities', volunteer_opportunities_path, class: 'mdl-navigation__link' %>
<% if user_signed_in? %>
<% if policy(:dashboard).elevated_user_dashboard? %>
<%= link_to 'Admin', dashboard_path, class: 'mdl-navigation__link' %>
<% else %>
<%= link_to 'My Application', apply_path, class: 'mdl-navigation__link' %>
<% end %>
<%= link_to 'Logout', logout_path, class: 'mdl-navigation__link' %>
<% else %>
<%= link_to 'Apply', apply_path, class: 'mdl-navigation__link' %>
<%= link_to 'Login / Sign up', '/auth/auth0', method: :post, class: 'mdl-navigation__link', id: 'login' %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="header">
  <nav class="navbar is-dark top-nav" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="<%= root_path %>">
        <strong><%= appname %></strong>
      </a>
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="top-navbar-menu">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div class="navbar-menu" id="top-navbar-menu">
      <div class="navbar-start">
        <%= link_to t('navigation.volunteer_opportunities'), 'volunteer_opportunities_path', class: 'navbar-item' %>
        <%= link_to t('navigation.apply'), 'dashboard_path', class: 'navbar-item' %>
      </div>

      <div class="navbar-end">
        <%= icon_link_to t('navigation.language'), change_language_path, '🌎', class: 'navbar-item', 'data-turbolinks': 'false' %>
        
        <% if user_signed_in? %>
          <%= icon_link_to t('navigation.logout'), logout_path, '👤', class: 'navbar-item' %>
        <% else %>
          <%= icon_link_to t('navigation.login'), auth0_login_path, '👤', class: 'navbar-item', method: :post %>
        <% end %>
        
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_notifications.html.erb
<section class="notifications">
  <% flash.each do |key, value| %>
    <div class="notification <%= global_flash_class(key) %>">
      <button class="delete"></button>
      <%= value %>
    </div>
  <% end %>
</section>

app/views/layouts/_page_structure.html.erb
<!-- Uses a header that scrolls with the text, rather than staying
  locked at the top -->
<div class="mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-layout__header--scroll">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Jazzify</span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation -->
      <nav class="mdl-navigation">
        <%= render 'layouts/nav_links' %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Jazzify</span>
    <nav class="mdl-navigation">
      <%= render 'layouts/nav_links' %>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <!-- Content goes here -->
    <div class="page-content  <%= controller_name %> <%= action_name %>">
      <%= yield %>
    </div>
    <footer class="mdl-mini-footer">
      <div class="mdl-mini-footer--bottom-section">
        <div class="mdl-logo">
          Jazzify &copy; 2021
        </div>
        <ul class="mdl-mini-footer__link-list">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Help', help_path %></li>
          <li><%= link_to 'Privacy Policy', privacy_policy_path %></li>
          <li><%= link_to 'Volunteer Code of Conduct', code_of_conduct_path %></li>
        </ul>
      </div>
    </footer>
  </main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jazzify</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

  <% if user_signed_in? %>
  <script type="text/javascript">Rollbar.configure({payload: {person: <%= raw (current_user_profile_rollbar_js) %> }});</script>
  <% end %>

  <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
  <script src="https://cdn.tiny.cloud/1/m9b7317397rdiqen2so9oxn71k4ipeug49y2kix6iq87huk5/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
  <%= javascript_include_tag "stepper.min", defer: true %>

  <% if controller_name == 'dashboard' && action_name == 'apply' %>
    <meta name="turbolinks-cache-control" content="no-cache">
  <% end %>
</head>
<body class="mdl-color--grey-100 mdl-color-text--grey-700">
  <%= render 'layouts/page_structure' %>
  <%= render 'layouts/toast' %>
</body>